# Generated by Django 2.1.2 on 2018-10-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Memberships', '0002_auto_20181023_1203'),
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='allowed_memebership',
        ),
        migrations.AddField(
            model_name='course',
            name='allowed_memberships',
            field=models.ManyToManyField(to='Memberships.Membership'),
        ),
    ]
